### ISSUE TITLE
unable to perform ocr

### ISSUE THREAD

**Issue by freakster00** [papermerge/papermerge-core#119]
![image](https://user-images.githubusercontent.com/121386692/221602246-f4f60c0e-f96e-4142-a8ee-3fe0d06658cc.png)

**Comment by freakster00** [comment]
docker run -p 8000:8000 \
    -e PAPERMERGE__MAIN__SECRET_KEY=abc \
    -e DJANGO_SUPERUSER_PASSWORD=123 \
    papermerge/papermerge:latest

i just used it to create a rest api server,But i am not getting access to ocr worker

**Comment by ciur** [comment]
In order to start the worker you need to use command "worker":
```
docker run -p 8000:8000
-e PAPERMERGE__MAIN__SECRET_KEY=abc
-e DJANGO_SUPERUSER_PASSWORD=123
papermerge/papermerge:latest worker
```
 When you don't specify any command, default one is "server".
For more [commands see this file here](https://github.com/papermerge/papermerge-core/blob/master/docker/prod/scripts/run.bash#L77).

**Comment by ciur** [comment]
But I don't thing there is any point in starting "worker" and "rest api server" separately as the won't be able to communicate with each other (for that you use redis). In order to start worker and backend I usually use docker compose.

https://docs.papermerge.io/Installation/docker-compose.html

**Comment by freakster00** [comment]
can i edit papermerge core and deploy?

**Comment by freakster00** [comment]
can running just rest api server starts worker itself ?
