### ISSUE TITLE
i just want to know whether starting this django application automatically runs worker or should we manually run runserver and then run worker

### ISSUE THREAD

**Issue by freakster00** [papermerge/papermerge-core#120]

**Comment by freakster00** [comment]
![image](https://user-images.githubusercontent.com/121386692/222936408-02256f09-b7a6-4d56-ad65-e60f496fdf6b.png)

**Comment by ciur** [comment]
You do, it is just in <repo root>/docker/dev folder.

    $ poetry install
    $ export DJANGO_SETTINGS_MODULE=config.settings
    $ export PAPERMERGE__MAIN__SECRET_KEY=1234
    $ export PAPERMERGE__REDIS__HOST=localhost  # for worker to connect to rest api server you need redis up and running
    $ export PAPERMERGE__REDIS__PORT=6379
    $ export PAPERMERGE__SEARCH__ENGINE=whoosh   # simple python search engine as lib, for dev env is ok
    $ cd docker/dev   # <--- manage.py file is here
    $ poetry run task server
    $ poetry run task worker

**Comment by freakster00** [comment]
thanks worked,

In version 2.0 I guess django superuser gets all the maximum roles like giving access and permission but here I dont see
,Should I manually need to create a user and give him all the permission ?
