### ISSUE TITLE
What is the easiest way of creating  a folder and giving access to a group of users by modifying present code

### ISSUE THREAD

**Issue by freakster00** [papermerge/papermerge-core#129]

**Comment by freakster00** [comment]
@ciur is this possible?

**Comment by ciur** [comment]
There is no easy way. What you are asking is a complex feature.
I updated the [roadmap](https://docs.papermerge.io/roadmap.html) and this feature will be added in 2.6.0.
If you want it faster - I am looking forward for a pull request from you.
