### ISSUE TITLE
Importer does not import files in directories.

### ISSUE THREAD

**Issue by dvonessen** [papermerge/papermerge-core#13]
Hey @ciur, thank you for your awesome project.
I found that if I am using Papermerge's importer for local files, I only can import files and not folder within files.

As a better example, I do have a folder structure like this
```bash
Bank/Sparkasse/Kontoauszug/Kontoauszug.pdf
``` 
It would be awesome if Papermerge is able to import this structure into Papermerge's internal structure. 
What do you think about this feature? I am not a fully fledged python dev, but maybe with some assistance, I can try to add this to the local importer function.

Thanks!

**Comment by ciur** [comment]
What you are asking is part of the plan in long term. However, this "feature" will not be part of the papermerge-core, instead it will be implemented as 3rd party application.

Let me explain:
The papermerge-core is fully RESTful API (to be exact, it is being changed to be fully RESTful). This means, basically, that all operations like creating folders, uploading documents, adding tags, triggering automates, creating users - all could be performed via HTTP requests. See for example the [latest update to the preferences endpoint](https://docs.papermerge.io/REST%20API/preferences.html).

As result of RESTful-ness of the papermerge-core, any person would be able to create 3rd party applications that will do whatever sort of import you/he/she likes :).
Regarding to your particular request, if not me, I think there will be other persons with minimal knowledge of python (curl, bash, any sort of HTTP client), who will create small command line application/utility/desktop/mobile app which will help you import documents preserving their folder structure - all thanks to REST API.

Here is an easy to understand explanation of what [REST API](https://www.youtube.com/watch?v=Q-BpqyOT3a8) is.

**Comment by dvonessen** [comment]
Yes, you are right. But right now, there is an importer function in the papermerge-core. Does that mean you will delete the current importer function from papermerge core and add it to an app?
I think if there is a function inside papermerge-core, it could be extended by this feature, so that there is no duplicate app that has to be maintained. 

Thank you.

**Comment by ciur** [comment]
>  Does that mean you will delete the current importer function from papermerge core and add it to an app?

Yes. The plan is to move Importer into another app (or to be exact into an external command line utility).
There are multiple reasons to do so:
1. this will simplify papermerge-core code.
2. this ease maintainability of the importer - for example of there is a bug specifically for the importer, you won't need to recreate the whole development environment of Papermerge, instead you will need to setup dev environment for little command line utility (which means you need to have just python installed)

**Comment by dvonessen** [comment]
Sounds great! Thank you for clarifying things.

Last question, is 2.1.0-alpha1 from hub.docker.com working? I know the term alpha, but to help finding issues, I think I could be a early adopter. 

Maybe I will write the `cli` to recursive upload documents to papermerge.
Right now I have about > 4k of files in a deeply directory structure.

**Comment by ciur** [comment]
Version tagged with 2.1.0-alpha1 is my first attempt to see how to start [all dependent services with docker-compose](https://github.com/papermerge/papermerge-core/tree/master/docker). Obviously you can try it, but the REST API documented here won't work in that docker image. Besides I did not document yet (for 2.1) how to play around with docker-compose. 
I need two more weeks time to complete 'alpha-2' and document how o try (very early version) of what's done so far.

**Comment by ciur** [comment]
Recursive folder import is available via [papermerge-cli import /path/to/some/folder](https://docs.papermerge.io/Command%20Line%20Utilities/cli.html#import-folders-documents) command line utility.
