### ISSUE TITLE
Update to Tesseract 5?

### ISSUE THREAD

**Issue by JVKeller** [papermerge/papermerge-core#147]
Hello. Has anyone tried this with tesseract 5? I'm getting terrible OCR accuracy.

BTW,,, thank you for your work on this! You have done a great job and I hope it goes places for you.

**Comment by ciur** [comment]
I didn't review tesseract 5 yet.

Papermerge does not use tesseract  command line tool directly though, instead it uses tesseract via excellent [ocrmypdf](https://ocrmypdf.readthedocs.io/en/latest/index.html) python package.

**Comment by JVKeller** [comment]
Yes, I saw that, and also noticed ocrmypdf 1.4+ uses tesseract5.

**Comment by ciur** [comment]
By the end of 2023
