### ISSUE TITLE
Fix compose file

### ISSUE THREAD

**Issue by gljones2001** [papermerge/papermerge-core#18]
I had to edit the compose file to fix an issue of Traefik not allowing me to access the webpage from another machine. 
I would get a `404 Page Not Found` error uintill i did the fix below.

1. Replace all instances of `papermerge.local` with `${HOSTNAME}` in `docker-compose.yml`
2. add `HOSTNAME=<hostname of PC>` to .env

**Comment by gljones2001** [comment]
You know, I just had the thought to instead of make it a .env value, to get the hostname from the PC itself. That might be easier.

**Comment by ciur** [comment]
@gljones2001 I would gladly accept your pull request with above mentioned fix :smile:

**Comment by gljones2001** [comment]
oh. I didn't have a pull request. I just manually fixed it by using the web editor in Portainer.

**Comment by gljones2001** [comment]
Honestly it was such a simple edit I thought you could just do it through the github web editor. I didn't want to do a whole pull request just for like 2 lines of code.

**Comment by gljones2001** [comment]
![image](https://user-images.githubusercontent.com/20365116/165597738-fa0ec251-9feb-491d-9463-5993129f0fe9.png)
![image](https://user-images.githubusercontent.com/20365116/165597782-f647834f-7ad2-4513-9826-04e5551e5a66.png)
There are the places I changed it.

**Comment by gljones2001** [comment]
Awesome dude. Thanks. I'll try it out.

**Comment by gljones2001** [comment]
Hey, you might want to update the setup page in the docs.
https://docs.papermerge.io/Installation/docker.html

**Comment by gljones2001** [comment]
Also, Noticed a descrepicy in the .env on the readme.
```
APP_IMAGE=ghcr.io/papermerge/papermerge
APP_TAG=latest
PAPERMERGE_JS_IMAGE=ghcr.io/papermerge/papermerge.js
PAPERMERGE_JS_TAG=latest

HOSTNAME=docman

DB_USER=postgres
DB_NAME=postgres
DB_PASSWORD=postgres
DB_HOST=db
DB_PORT=5432

REDIS_HOST=redis
REDIS_PORT=6379

ES_HOSTS=es
ES_PORT=9200

SECRET_KEY=alsdkalsdjlaksdj90823423!KLKJLkjkjlkjlKLPOgrwqna

SUPERUSER_USERNAME=admin
SUPERUSER_EMAIL=admin@mail.com
SUPERUSER_PASSWORD=password
```
Notice the `ghcr.io/` that is not on the readme.

**Comment by ciur** [comment]
good catch
