### ISSUE TITLE
Can not login anymore

### ISSUE THREAD

**Issue by Nuube** [papermerge/papermerge-core#209]
I juste restarted my docker container. Now I can not login in anymore.

Beneath the login screen I get an error message.

`SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON`

(BTW: I needed do delete the cookies in my browser before that, otherwise the login screen just stayed an empty grey background without the login pop-up)

**Comment by ciur** [comment]
can you check web inspect (chrome/firefox developer tools -> inspect) -> network and tell here the response from the server ? 
Also docker logs will help a lot (docker logs <container ID>).

**Comment by Nuube** [comment]
Does this help?

![2023-09-23_21-23](https://github.com/papermerge/papermerge-core/assets/25643142/3685eee3-db0a-4352-8245-4c3f77f7d06d)

**Comment by ciur** [comment]
Maybe you give a try to version 3?

via docker: https://papermerge.github.io/documentation/3.0-dev/setup/docker/
via docker compose: https://papermerge.github.io/documentation/3.0-dev/setup/docker-compose/
or ansible: https://papermerge.github.io/documentation/3.0-dev/setup/ansible/

I will officially release version 3.0 by the end of current month (December, 2023)
