### ISSUE TITLE
Papermerge behind Traefik v2 transparent proxy

### ISSUE THREAD

**Issue by robin-collins** [papermerge/papermerge-core#224]
Hello,

I run all my containers behind a transparent proxy to provide https and dns (eg container.mysubdomain.mydomain.tld)

I modified the docker-compose.yml file for the elastic search version. 

The app starts up and works as I think it should, but here and there errors start to occur, like creating a API key didn't show the key the first time, deleting a key gets the front end stuck and leaves me having to delete cookies to re log back in.

I have attached a copy of my docker-compose file for reference. 

Any assistance greatly appreciated.

[papermerge_docker-compose.yml.txt](https://github.com/papermerge/papermerge-core/files/12875804/papermerge_docker-compose.yml.txt)

**Comment by ciur** [comment]
Can you please attach ``docker logs`` of app + worker container(s)?

**Comment by ciur** [comment]
Silence, silence...
