### ISSUE TITLE
Drag 'n' Drop not working

### ISSUE THREAD

**Issue by smichaelsen** [papermerge/papermerge-core#256]
![papermerge-drag-drop(1)](https://github.com/papermerge/papermerge-core/assets/912435/2a1e07ff-0aa1-4af2-aedb-d26fcb38d88c)

I'm trying out papermerge for the first time and set up a test installation with docker compose on a hetzner machine. Drag 'n' Drop doesn't work for me. The browser just opens any PDF document instead. Tested with Firefox and Chrome on macOS.

The console shows this error in Chrome:

![Screenshot 2023-11-21 at 11 07 43](https://github.com/papermerge/papermerge-core/assets/912435/ec4c157a-7949-42ac-a7b3-6a952fe35d4f)

Is there anything I can do to resolve this?

**Comment by ciur** [comment]
Maybe you give a try to version 3?

- via docker: https://papermerge.github.io/documentation/3.0-dev/setup/docker/
- via docker compose: https://papermerge.github.io/documentation/3.0-dev/setup/docker-compose/
- or ansible: https://papermerge.github.io/documentation/3.0-dev/setup/ansible/

I will officially release version 3.0 it in a month or so.

**Comment by smichaelsen** [comment]
Indeed in v3 it works better. This resolves the issue _for me_. Thank you!
