### ISSUE TITLE
Python 3.9 Support

### ISSUE THREAD

**Issue by telsch** [papermerge/papermerge-core#33]
Are there reasons to stay at python 3.8? would be great if you could raise the max version to 3.9. when I saw correctly, configula and OCRmyPDF_papermerge are also affected. The main reason for this would be the use of [piwheels](https://www.piwheels.org) for simplified ARM builds based on Python 3.9 wheels for Bullseye.

**Comment by ciur** [comment]
Thank you for opening the bug. I will take care of this soonest.

**Comment by ciur** [comment]
@telsch please could you please confirm if above changes fix your issue ?

**Comment by telsch** [comment]
Yep it's solved ;)
