### ISSUE TITLE
Will rules return?

### ISSUE THREAD

**Issue by maxulm** [papermerge/papermerge-core#380]
Hi, 

do you have any plans about a return of the rules in 3.x?

Regards
Max

**Comment by ciur** [comment]
yes, they will return

**Comment by maxulm** [comment]
Great! Do you have a roadmap or target version?

**Comment by maxulm** [comment]
Sad to hear this, but understand your point.

**Comment by maxulm** [comment]
Will it be Part of 3.3?

**Comment by ciur** [comment]
Unfortunately no.

**Comment by maxulm** [comment]
And the implemention is no longer planned for Future Versions?

**Comment by ciur** [comment]
It is.

The "rules", or I guess you are referring to former "automates" will be back in future as part of "workflows".
In short, rules = automates = workflows .

Automates will be back, by end of 2025. They will be full featured workflows.

Higher priority features which will be there in 2025:

-  custom fields (so called metadata) - will be released by end of this months, in 3.3
- localization (will be out in December 2024); the application will have UI in English and German.
- resource sharing i.e. sharing of folders, documents, tags, custom fields and document types with other users and groups (this feature will be released in 2025).

**Comment by maxulm** [comment]
Ah, ok!
Yeah, I‘m Talking about the automates!
Thank you :)
