### ISSUE TITLE
Cannot Login Into New Installation

### ISSUE THREAD

**Issue by zhaobozb** [papermerge/papermerge-core#49]
Hi I have difficulties to login to new installation with the below error:

![Screenshot from 2022-08-22 12-46-13](https://user-images.githubusercontent.com/12931635/185976248-15fe7f9a-96fa-4899-ae3b-bc2168753404.png)

Do you have any idea to solve it?  Thank you very much.

Below are the logs:
* [_papermerge-db-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396175/_papermerge-db-1_logs.txt)
* [_papermerge-redis-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396181/_papermerge-redis-1_logs.txt)
* [_papermerge-es-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396182/_papermerge-es-1_logs.txt)
* [_papermerge-frontend-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396183/_papermerge-frontend-1_logs.txt)
* [_papermerge-ws_server-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396184/_papermerge-ws_server-1_logs.txt)
* [_papermerge-backend-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396185/_papermerge-backend-1_logs.txt)
* [_papermerge-worker-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396186/_papermerge-worker-1_logs.txt)
* [_papermerge-traefik-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396187/_papermerge-traefik-1_logs.txt)

**Comment by zhaobozb** [comment]
Hi I have difficulties to login to new installation with the below error:

![Screenshot from 2022-08-22 12-46-13](https://user-images.githubusercontent.com/12931635/185976248-15fe7f9a-96fa-4899-ae3b-bc2168753404.png)

Could you please help me solve it?  Thank you very much.

Below are the logs:
* [_papermerge-db-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396175/_papermerge-db-1_logs.txt)
* [_papermerge-redis-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396181/_papermerge-redis-1_logs.txt)
* [_papermerge-es-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396182/_papermerge-es-1_logs.txt)
* [_papermerge-frontend-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396183/_papermerge-frontend-1_logs.txt)
* [_papermerge-ws_server-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396184/_papermerge-ws_server-1_logs.txt)
* [_papermerge-backend-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396185/_papermerge-backend-1_logs.txt)
* [_papermerge-worker-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396186/_papermerge-worker-1_logs.txt)
* [_papermerge-traefik-1_logs.txt](https://github.com/papermerge/papermerge-core/files/9396187/_papermerge-traefik-1_logs.txt)

**Comment by ElQDuck** [comment]
This is because your frontend cant reach the backend. How did you install papermerge?
This problem and how to fix it is described here: [Papermerge for DevOps - Part 1 - Introduction](https://youtu.be/h8IQk8ne87Q?t=287)
