### ISSUE TITLE
Making requests to the REST API

### ISSUE THREAD

**Issue by josedurigon** [papermerge/papermerge-core#508]
Ok, so this is not so much an issue as a request for help.

I've set up the Papermerge containers using the YAML file with docker-compose provided in the documentation, and the application itself works flawlessly—great job on that!

However, I’m having trouble testing the API endpoints using Postman. Here’s what I’ve done so far:

I generated a token for the pre-defined user "john" with the password "hohoho". The token was generated successfully.
I’m running Papermerge on localhost:12000.
When I make requests to /users (and similar endpoints) from Postman, I include the token as a Bearer token in the Authorization header.
The container logs show status 200 when I send requests, but in Postman, the response is an HTML page prompting for JavaScript to be enabled. This HTML response occurs for other endpoints as well, even if the container logs show status codes like 200 or 403.

I’m trying to confirm the API functionality and test the endpoints in Postman before integrating them into another application. I suspect it may be related to headers or token scopes, but I’m not certain what might be causing the HTML responses instead of JSON.

Any insights on how to successfully get JSON responses or what might be causing this behavior would be greatly appreciated!

Thank you in advance!

**Comment by ciur** [comment]
What papermerge version do you use ?
How does your http request look like ?
Did you include "Content-Type" header ? i.e. "Content-Type: application/json" ?

**Comment by ciur** [comment]
Closing the ticket because of inactivity.
