### ISSUE TITLE
Authentication credentials were not provided

### ISSUE THREAD

**Issue by luyuanerp** [papermerge/papermerge-core#51]
Backend and Frontend start normally, but an error occurs when accessing the front-end page chrome console, http://120.76.102.100:8000/api/users/me/ 401 (Unauthorized) error 。

Visit http://120.76.102.100:8000/api/users/me/ and return information "errors":[{"detail":"Authentication credentials were not provided.","status":"401","source": {"pointer":"/data"},"code":"not_authenticated"}]}

<img width="735" alt="186361522-7902c245-86d5-4c6f-9a76-77a67d0e0647" src="https://user-images.githubusercontent.com/75401343/186606910-df6a4250-0b3c-4dfc-b17a-a5a20587551a.png">

<img width="890" alt="image" src="https://user-images.githubusercontent.com/75401343/186630422-951d6375-9e1e-491d-81a4-78ae36e19c93.png">

Docker Compose deployment and operation also have this problem, please help, thank you!
<img width="932" alt="image" src="https://user-images.githubusercontent.com/75401343/186705895-12799877-ef6d-4162-b67e-ba458cfdbe27.png">
<img width="753" alt="image" src="https://user-images.githubusercontent.com/75401343/186706518-6cdee966-0418-45a6-96c3-745bd6273e2a.png">

**Comment by ciur** [comment]
This is frontend bug manifested is due to "outdated cookie".
Workaround for it is to delete "ember_simple_auth-session" cookie like in short demo below:

![unauth-delete-cookie](https://user-images.githubusercontent.com/24827601/187123012-c31dc778-d89d-4582-8898-2e3ca2c8d505.gif)

**Comment by ciur** [comment]
This issue is obsolete. Papermerge 3 does not use ember for frontend anymore (switched to react).
