### ISSUE TITLE
Security issue - IDOR

### ISSUE THREAD

**Issue by looCiprian** [papermerge/papermerge-core#57]
Hi! I've noticed that the _document-versions/<uuid:pk>/download/_ API is vulnerable to [IDOR](https://portswigger.net/web-security/access-control/idor) vulnerability allowing any user to download any file.

I've tried to download a file uploaded by the admin account (and only visible to the admin account) using a low-privileged user, and the file was successfully downloaded

**Admin view:**
![1](https://user-images.githubusercontent.com/30753137/188509205-84e4ebcb-5734-4caa-9a05-16a1264e2661.png)

**User view:**
![2](https://user-images.githubusercontent.com/30753137/188509238-ebe4cf33-0f3c-4b46-9ec4-7d85a23e45ad.png)

**Downloading admin file using direct url from the user account:**
![3](https://user-images.githubusercontent.com/30753137/188509261-6b7574ea-64ef-4b64-adeb-f52f8f6c1f94.png)

Can you verify the issue, please?
Thanks!

**Comment by ciur** [comment]
Thank you for reporting the issue, I will check!

**Comment by ciur** [comment]
@looCiprian, I was able to reproduce the problem. Actually I could access the document version file even without being authenticated !  :scream: 

It's fixed and and will be part of next beta increment (2.1.0b4 I guess?).

**Comment by looCiprian** [comment]
Thanks for fixing it!
