### ISSUE TITLE
PDF file Upload

### ISSUE THREAD

**Issue by ChristophNow** [papermerge/papermerge-core#71]
Hi,

PDF file with a size of 100 MB are not uploaded for me. Is this a known problem?

<img width="806" alt="image" src="https://user-images.githubusercontent.com/78483710/190668741-39abb61c-5380-4151-9093-824cac599184.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/78483710/190669533-cb44d374-b3f7-4a48-9ff3-684442dd1c90.png">

with kind regards 
Chris

**Comment by ciur** [comment]
This is papermerge 2.0.

From screenshot image I see that you are using Apache server.
Such limits (as size of the POST body i.e. "request entity") usually are configurable by webservers. In your case it is Apache.

**Comment by ChristophNow** [comment]
Exactly I use Apache
I use the docker container

In which path can you adjust the maximum upload size on apache?

Unfortunately I found on Google only something related to PHP and WP

**Comment by philtreF** [comment]
Did you solved this since september ?
You should have a look on these apache httpd directives https://httpd.apache.org/docs/2.4/en/mod/core.html 
`LimitRequestBody` and others.
