### ISSUE TITLE
Add multiple OCR languages

### ISSUE THREAD

**Issue by Fabiettus** [papermerge/papermerge-core#75]
Hi, it's possible to have an official worktrough to add multiple ocr languages in papermerge? 
Many thank's,
Fabio.
**labels: docker, documentaion** (sorry i can't add labels by myself)

**Comment by ciur** [comment]
Yes, this information should be part of the documentation.

**Comment by ciur** [comment]
Documentation [updates are now available online](https://docs.papermerge.io/Installation/docker.html#adding-ocr-languages-to-the-docker-image).
Please use [Papermege docker image 2.1.0b5 or newer](https://github.com/papermerge/papermerge-core/pkgs/container/papermerge)
